### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/mkdocstrings#1]
The code is ugly :nauseated_face: 

Ideally, we would use the same approach as [mkautodoc](https://github.com/tomchristie/mkautodoc): with a Markdown extension.
- we would directly manipulate an HTML tree (much, much cleaner)
- we could get rid of the markdown extensions requirements

But:
- there's no easy way to automatically register an extension from a plugin (or is there? https://github.com/mkdocs/mkdocs/issues/1942)
- we would need to change the object references logic (currently in two passes: `on_nav` builds all objects and references, `on_page_markdown` appends all references to all pages containing autodoc instructions). Using a markdown extension, we would need to pass information from the plugin to the extension (the objects references), and I'm not sure if this is easy or even possible (see previous point).
- we would maybe need to import `codehilite`, `inlinehilite` and other functions to replicate the related and currently required markdown extensions

General improvements to do:
- be more robust: catch exceptions, log warnings and fail gracefully when information is missing (types, annotations, etc.) or not in the right format (parameters types in docstrings, etc.)
- refactor type/annotation related functions: there are currently a few functions to get the return type, the parameters type, the signature, etc. It could be way more compact and elegant.
- use subclasses for the different objects categories: Function, Method, Attribute, Module and Class. Probably Type (name + path for automatic reference), Parameter (name + type + description + default), Return (type + description) and Exception (type + description) as well (find another name for Exception hehe)

Ideally we would still proceed in two steps:
1. build all the necessary data in the `on_nav` event
2. render it directly to HTML with a markdown extension having access to the data

**Comment by pawamoy** [comment]
Update: we are now discarding HTML in `on_nav` event, and re-converting the whole file + generated markdown from docstrings to HTML, with a custom markdown converter. It allows us to drop the markdown extensions requirement, as we use our own converter.

**Comment by shyamd** [comment]
Won't that break compatibility with other themes?

**Comment by pawamoy** [comment]
If I understand correctly, it should not, because themes are only HTML files (Jinja2 templates actually). They are only supposed to insert the generated HTML contents in some section of the complete HTML page.

But maybe I'm wrong! In what way do you think this could break?

**Comment by pawamoy** [comment]
Just tried the built-in readthedocs theme, it seems fine, except some formatting issues with code blocks (they seem not to be horizontally scrollable, so long lines go out of the main div, and line numbers are missing at the beginning and the end of code blocks). But I don't think it has anything to do with the way we render the HTML in mkdocstrings.

**Comment by pawamoy** [comment]
If you're talking about compatibility with other **plugins** and not themes, then yes, maybe it's not compatible. I guess this is the trade-off with plugins. Their order of execution has an incidence on the final output.

But even in that case, I'm not sure if it could easily break things.

- If another plugin is modifying markdown *before* mkdocstrings, in `on_page_markdown`, mkdocstrings `on_page_contents` should pick these modification from `page.markdown`, and render them naturally with our markdown converter + combined extensions.
- If the other plugin is running *after* mkdocstrings, then it depends on the order of execution of mkdocs:
  - every plugin `on_page_markdown`, then every plugin `on_page_contents`: should be fine
  - an other order of execution does not make sense I guess? you cannot render markdown to HTML in one plugin, then again markdown to HTML in another one...
- if another plugin is modifying HTML contents *before* mkdocstrings, then yes, these modifications would be lost, since mkdocstrings re-render the HTML from `page.markdown`
- if the other plugin is modifying HTML contents *after* mkdocstrings, then it should be fine

From the top of my head I could only find one case where mkdocstrings' way of rendering HTML could be problematic. If such a problem arises, it will need proper investigation (do we want to be compatible with every other plugin?).

**Comment by shyamd** [comment]
That makes sense. Plugins appear to be far more powerful and consequently require a lot more care in terms of how they work together. Will the conversion to pure extension alleviate some of these issues?

**Comment by shyamd** [comment]
Also, it may be useful to be able to either detect loaded extensions or turn on/off the features that require these other extensions.

**Comment by pawamoy** [comment]
The conversion to a pure markdown extension would likely solve this particular problem, but would bring its own lot of difficulties. There is a lot to say about all this. I think what we need is a proper document describing the different possible implementations, their advantages and disadvantages. I'll try to get some time to write such a document these next days.

**Comment by pawamoy** [comment]
Let's continue the conversion in #28.
