### ISSUE TITLE
Add Options to Documentation

### ISSUE THREAD

**Issue by dbanty** [pawamoy/mkdocstrings#104]
**Is your feature request related to a problem? Please describe.**
I had to poke around at a combination of source code, and other issues to figure out which options could be configured and how to configure them. In my particular case I was both trying to filter out dunder methods and turn off `show_root_full_path`.

**Describe the solution you'd like**
I'd like to see a section in the docs that describes both global options and Python-specific options and shows where/how to put the values (e.g. the mkdocs.yml and under the `:::module`).

**Comment by pawamoy** [comment]
Yes, documentation must be improved. It's on my TODO list :wink: Thanks for the feedback!

**Comment by pawamoy** [comment]
I improved the docs a bit: [Usage](https://pawamoy.github.io/mkdocstrings/usage) and [Python handler](https://pawamoy.github.io/mkdocstrings/handlers/python).

Please open issues if you feel some things are missing! :slightly_smiling_face:
