### ISSUE TITLE
Error: module 'mkdocstrings' has no attribute 'makeExtension'

### ISSUE THREAD

**Issue by chbndrhnns** [pawamoy/mkdocstrings#109]
**Describe the bug**
After following the instructions to install and activate the plugin, `mkdocs serve` fails:

```
INFO    -  Building documentation...
DEBUG   -  Loading configuration file: /Users/powerjo/dev/juice/juiceutils/mkdocs.yml
ERROR   -  Config value: 'markdown_extensions'. Error: Failed to initiate extension 'mkdocstrings': module 'mkdocstrings' has no attribute 'makeExtension'
```

**To Reproduce**
- Python 3.8
- mkdocs 1.1
- mkdocs-material 5.1.6

mkdocs.yml:

```
<snip>
markdown_extensions:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - juiceutils
```

**Expected behavior**
The plugin can be used.

**Screenshots**

**Information (please complete the following information):**
- Browser: [e.g. chrome, safari]
- `mkdocstrings` version: [e.g. 0.10.2] 

**Additional context**

**Comment by chbndrhnns** [comment]
My error. I put the config snippet in `markdown_extensions:` instead of `plugins:`

**Comment by pawamoy** [comment]
I couldn't answer earlier, glad you found the solution :wink:

Thank you for coming back, explaning what was wrong and closing the issue!

**Comment by maciejmatczak** [comment]
Thanks @chbndrhnns , literally did the same right now ;)
