### ISSUE TITLE
Can I collect classes for documentation based on a custom function?

### ISSUE THREAD

**Issue by chbndrhnns** [pawamoy/mkdocstrings#111]
I would like to add all classes that inherit from a specific class to one Markdown page. Would it be possible to have some kind of custom collector that executes a python method and generates the documentation for the items that are given in the return value?

**Comment by pawamoy** [comment]
Hello! It's not possible, no. I wonder if allowing to use custom, local handlers would be a good idea. As a workaround, you could always write a script that generate the Markdown pages for you. I'll think about this a bit more later and hopefully with come back with better hints.

**Comment by pawamoy** [comment]
Hey again! I'm going to close this issue as I don't see an obvious way to allow what you would like to do. Feel free to open a new feature request with a design proposition, I would consider it :slightly_smiling_face:
