### ISSUE TITLE
Dataclasses

### ISSUE THREAD

**Issue by rossmechanic** [pawamoy/mkdocstrings#116]
@pawamoy at this point I'm going to be your top issue contributer!

I'm starting to document some of the dataclasses we use, and was hoping for a way to easily specify a dataclass and have the docs show an optional docstring with each of the parameters of the dataclass. At the moment, it just shows the unformatted `repr` of the dataclass. Any ideas here?

**Comment by pawamoy** [comment]
### :1st_place_medal: And the Top Issue Contributor Medal goes toooooo.... @rossmechanic :tada:

**Comment by pawamoy** [comment]
Currently we do not pick up descriptions for dataclasses fields, but this will be fixed with https://github.com/pawamoy/pytkdocs/issues/30 and https://github.com/pawamoy/pytkdocs/issues/33 :slightly_smiling_face:

**Comment by rossmechanic** [comment]
@pawamoy https://github.com/pawamoy/pytkdocs/blob/master/src/pytkdocs/loader.py#L368
what is that section of the code if not picking up dataclasses?

**Comment by pawamoy** [comment]
It *should* pick up dataclasses, but it does not pick up the descriptions of the dataclass fields (if any). Sorry if this wasn't clear.

I actually didn't try that feature, could you send a screenshot to see how it looks? And paste the dataclass code (removing unneeded/sensitive contents of course)?

**Comment by rossmechanic** [comment]
Don't really care about the descriptions of the dataclass fields as much as the fields and their types/defaults. Doesn't seem to get the source code of the dataclasses at all. Might be an issue with the fact that they're defined using a decorator?

Dataclass code:
```
@dataclass(frozen=True)
class MyDataClass:
    my_int: int = 0
```

<img width="253" alt="Screen Shot 2020-05-21 at 3 15 39 PM" src="https://user-images.githubusercontent.com/6855461/82596847-09bc4100-9b76-11ea-9f2a-07780272fbc5.png">

**Comment by pawamoy** [comment]
I couldn't find the time to investigate yet. Will try the coming week :slightly_smiling_face:

**Comment by pawamoy** [comment]
I tried with pytkdocs v0.5.0, does it look good? Could you try it? mkdocstrings doesn't accept pytkdocs v0.5.0 yet, but you can always do `poetry run pip install -U pytkdocs` if you use poetry and want to install without checking version compatibility.

![Screenshot_2020-06-08_22-30-29](https://user-images.githubusercontent.com/3999221/84077919-53ab8080-a9d8-11ea-9359-8d3fb1499f67.png)

**Comment by pawamoy** [comment]
> Doesn't seem to get the source code of the dataclasses at all.

Did you actually wanted to get the "Source code" collapsible div? I don't think we allow to do that for classes yet.

**Comment by chbndrhnns** [comment]
Could I force mkdocstrings somehow to handle [pydantic models] in the same way as dataclasses?

I would like to see that I can create a class and the type arguments are derived from class constants, like this:

```python
from pydantic import BaseModel

class MyModel(BaseModel):
    """
    Arguments:
        api_exception: Exception class
    """"

    api_exception: str = 'Exception'
```

**Comment by pawamoy** [comment]
Pydantic models are already supported, and soon MkDocstrings will support Google-style `Attributes` section (which you would use here instead of `Arguments`) :slightly_smiling_face:

**Comment by chbndrhnns** [comment]
> Pydantic models are already supported, and soon MkDocstrings will support Google-style `Attributes` section (which you would use here instead of `Arguments`) 🙂

This looks very nice! Thanks! Would it be possible to add the defaults given for the attributes?

**Comment by pawamoy** [comment]
Sure, please open a new feature request on [pytkdocs](https://github.com/pawamoy/pytkdocs/issues/new)!

**Comment by chbndrhnns** [comment]
https://github.com/pawamoy/pytkdocs/issues/50

**Comment by rossmechanic** [comment]
@pawamoy Running pytkdocs 0.5.2 and mkdocstrings 0.12.0, and still getting the same issues I was getting before.

While looking at this, I also saw an Enum. The description was just `An enumeration.` Any plans to make that show all the options?

**Comment by pawamoy** [comment]
You see `MyDataClass(my_int: int = 0)` in the generated docs because that's what the dataclass sets as a docstring. Add a docstring to your dataclass and it will be displayed. Now I guess the attributes aren't shown because you don't define docstrings below them either. You could try to use the [`show_if_no_docstring` option](https://pawamoy.github.io/mkdocstrings/handlers/python/#rendering), but something even better would be to declare an `Attributes` section in your class docstring, so the attribute appear in a table :slightly_smiling_face: See https://github.com/pawamoy/mkdocstrings/issues/130

**Comment by rossmechanic** [comment]
Ah, that worked. Thanks!!
