### ISSUE TITLE
how to support different docstring style (Numpy docstrings)

### ISSUE THREAD

**Issue by hcoohb** [pawamoy/mkdocstrings#118]
I think this project creates great documentation, congratulations.
But I feel it is a pity I cannot use it since it seems only the google-style docstrings are supported by pytkdocs. Numpy style docstrings are quite popular these days and so far I cannot see a good nkdocs plugin for generating API docs with them.

If we create a new parser for numpy as is mentioned [here](https://github.com/pawamoy/pytkdocs/issues/7#issuecomment-624767403). 
How do we go about using it in mkdocstrings?
Is there a setting ready for changing the docstring of the python handler?

Thanks

**Comment by pawamoy** [comment]
The next version of mkdocstrings will accept pytkdocs v0.5.0, which itself accepts `docstring_style` and `docstring_options` options, which means they will be directly available in mkdocstrings as every option under the `selection` key is passed to the handler's collector (pytkdocs in the Python case).

Therefore I'll close this issue as it will be resolved with the next release. Feel free to comment if you would like more details :slightly_smiling_face:

**Comment by sdtaylor** [comment]
A google search brought me here so I'm just commenting with the solution. You need to install `pytkdocs` like so:  

`pip install 'pytkdocs[numpy-style]>=0.5.0'`

Then set the style inside selection

```
::: my_package.my_module
    selection:
      docstring_style: numpy
```

**Comment by rozsasarpi** [comment]
Also see this on how to set the style for the entire documentation: https://github.com/mkdocstrings/mkdocstrings/issues/278#issuecomment-831411193
