### ISSUE TITLE
Different behavior on Linux and OSX of mkdocstrings.handlers.CollectionError

### ISSUE THREAD

**Issue by CarlosVaquero** [pawamoy/mkdocstrings#125]
When running the same mkdocs.yml and project from the same directory and specifying the PYTHONPATH in the `mkdocs` build I have different behaviors when in a Linux server than in my local OSX laptop. 

`PYTHONPATH='../src' mkdocs build`

In particular, in my OSX laptop I receive the following:

` mkdocstrings.handlers.CollectionError module 'mylibrary.mymodule' has no attribute 'mypythonfile_withclasses'`

But in the linux server I can build it without a problem. 

I have installed the requirements in both conda environments but the result is different. Any tip on what could be causing this issue?

ps . If I don't use mkdocstrings, I can build the mkdocs project in both the server as local.

**Comment by pawamoy** [comment]
I'll add OSX jobs in CI. Could you share the code triggering the error please?

**Comment by pawamoy** [comment]
CI is passing for macos-latest for both mkdocstrings and pytkdocs. I'll need some code to try and understand what is going on :slightly_smiling_face:

**Comment by chbndrhnns** [comment]
Regarding mac os, I need to set `export PYTHONPATH=.:$PYTHONPATH` to make mkdocstrings work. I would want to get around that :)
