### ISSUE TITLE
@lru_cache decorated methods are not supported

### ISSUE THREAD

**Issue by chbndrhnns** [pawamoy/mkdocstrings#126]
**Is your feature request related to a problem? Please describe.**
I would like to see documentation generated for such an example:

```python

@lru_cache
def my_method(inp: int) -> str:
    """my method"""
    return str(inp)
```

For now, I only see this error:

```
mkdocstrings.handlers.CollectionError: juiceutils.registries.get_repo_registry: <class 'functools._lru_cache_wrapper'> not yet supported
```

**Describe the solution you'd like**
I would like to see support for that

**Describe alternatives you've considered**
Cannot think of any

**Additional context**
n/a

**Comment by pawamoy** [comment]
What version of pytkdocs and mkdocstrings are you using? [It should already be fixed](https://github.com/pawamoy/pytkdocs/issues/32)

**Comment by chbndrhnns** [comment]
I can see it works with mkdocstrings 0.12 👍
