### ISSUE TITLE
Numbering starts at 1 each time in examples

### ISSUE THREAD

**Issue by chbndrhnns** [pawamoy/mkdocstrings#137]
**Describe the bug**

When using numbered steps in the examples section, pieces of code resets the numbering counter to 1.

**To Reproduce**
Use this example:

```
def method():
    """
    Bla

    Examples:
        1. Do this

        >>> print('this')

        2. Do that

        >>> print('that')

        3. Third step

        4. Fourth step
    """

```

**Expected behavior**
I expect the numbers to be consecutive

**Screenshots**
![Screenshot 2020-07-21 14 37 31](https://user-images.githubusercontent.com/7534547/88055950-13572a80-cb60-11ea-889e-9c6c75355280.png)

**Information (please complete the following information):**
- OS: macOS
- Browser: Chrome
- `mkdocstrings` version: 0.12.1

**Additional context**

**Comment by jaredkhan** [comment]
Content within the list item point needs to be indented to indicate that it's part of the list item.

Then, as far as I can tell, the `>>>` syntax is not actually recognised by mkdocstrings at any point so it's just interpreted as a triple-nested quote! To have it interpreted as code, you can indent it yet again. Final indentation looks like this:


```
def method():
    """
    Bla

        >>> code here

    Examples:
        1. Do this

                >>> print('this')

        2. Do that

                >>> print('this')

        3. Third step

        More words here

        4. Fourth step
    """
    pass
```

**Comment by chbndrhnns** [comment]
Thanks for the hint with adding another indentation level. This fixes the numbering issue. However, the code formatting is broken on my side. I'll open another issue for that.

**Comment by chbndrhnns** [comment]
Code formatting issue: https://github.com/pawamoy/mkdocstrings/issues/138

**Comment by pawamoy** [comment]
Hi all!

So indeed it's a Mardown issue. Your items were separates by blocks with same indentation, therefore the Markdown parser starts again at `1.` each time.

Just a note: mkdocstrings (pytkdocs really) does actually recognize doctests (lines starting with `>>>` and all the next ones until a new line is met, or the end of the docstring).

Thanks for the help! I'll continue on the other issue.

**Comment by pawamoy** [comment]
I was on mobile before - thanks again @jaredkhan for the help, and @chbndrhnns for closing the issue :slightly_smiling_face:
