### ISSUE TITLE
Class Attributes won't be rendered as a table

### ISSUE THREAD

**Issue by nanogennari** [pawamoy/mkdocstrings#139]
When attributes are placed on a class docstring it won't be redered as a table:

![2020-07-23 17 39 24 127 0 0 1 79d44d9189f3](https://user-images.githubusercontent.com/1216281/88336499-7b963f80-cd0b-11ea-9918-f278fe3dfcf6.png)

If i place the same attributes on a method it is rendered as table:

![2020-07-23 17 42 03 127 0 0 1 99bbc9d081a0](https://user-images.githubusercontent.com/1216281/88336690-d6c83200-cd0b-11ea-8dd3-3f6f1776420d.png)

The used docstring:

    class community:
        """ Main class: initialized and evolves a community 

        Attributes:
            given_parameters (dict): 
            parameters (dict): 
            initOk (np.array): 
            simOk (bool): 
            random_seed (int):
            randgencom (Generator): 
        """
        def __init__(self, skip_triage=False, **parameters):
            """Community class initialization.

            Attributes:
                given_parameters (dict): 
                parameters (dict): 
                initOk (np.array): 
                simOk (bool): 
                random_seed (int):
                randgencom (Generator): 

            Args:
                parameters** (dict): Parameters dictionary for the simulation
                skip_triage (bool, optional): Skips parameters triage (code might not work)
            """

**Comment by pawamoy** [comment]
I see an extra space at the beginning of your class docstring. Could you try to remove it and see if it works better? It might be confusing the parser on the indentation.

**Comment by nanogennari** [comment]
Removed the space:

    class community:
        """Main class, initialize and evolves a community 

        Attributes:
            given_parameters (dict): 
            parameters (dict): 
            initOk (np.array): 
            simOk (bool): 
            random_seed (int):
            randgencom (Generator): 
        """

The result is the same.

**Comment by pawamoy** [comment]
Can you confirm you don't have extra spaces at the end of the `Attributes:` line, and that you don't mix tabs and spaces in the docstring?

I'm on mobile right now, debugging is not possible :sweat_smile:

I'll try things tomorrow :)

**Comment by nanogennari** [comment]
No extra spaces, all my indentations are made with spaces.

No hurry, this documentation probably won't go public for a few weeks...

**Comment by idfx** [comment]
I have the exact same issue and can confirm the same rendering of class attributes.

**Comment by pawamoy** [comment]
OK so it's in fact already fixed in pawamoy/pytkdocs#55, I just need to release version 0.6.1 :)

**Comment by nanogennari** [comment]
> OK so it's in fact already fixed in [pawamoy/pytkdocs#55](https://github.com/pawamoy/pytkdocs/pull/55), I just need to release version 0.6.1 :)

I've manually done the same fix as in the link above and the bug is gone, waiting for the new release.

**Comment by pawamoy** [comment]
Just released pytkdocs 0.7.0 and mkdocstrings 0.12.2 accepting it.
