### ISSUE TITLE
Unwanted whitespace in description of parameters section

### ISSUE THREAD

**Issue by yanniskatsaros** [pawamoy/mkdocstrings#142]
__`mkdocstrings` version `0.12.2`__

Hello, when generating documentation from my docstring it appears that there is unwanted whitespace being generated for the "description" as shown in the screenshot below. This is being generated from the following source code. I've been checking examples from the `mkdocstrings` [source code](https://github.com/pawamoy/mkdocstrings/blob/master/src/mkdocstrings/plugin.py#L233) and documentation and can't seem to find anything wrong in my formatting. Can anyone please help me out? Thanks in advance!

```python
class Project:
    # ...

    @classmethod
    def from_json(cls, path: str):
        """
        Initializes a new project directly from an `analysis.json` file.
        
        !!! info "See Also"
            [`Project.__init__`](#reportpress.__init__.Project.__init__)

        Arguments:
            path: The path to the JSON file
        """
        import json

        with open(path, 'r') as f:
            p = json.load(f)

        return cls(p)
```

## Example

![image](https://user-images.githubusercontent.com/32942328/88837878-59cf0980-d19e-11ea-9a5b-cffb80c4c0a1.png)

## Documentation Structure

```
docs/
├── api
│   ├── __init__.md
│   ├── analysis.md
│   ├── cli.md
│   └── data.md
├── changelog.md
├── img
│   ├── cli-walkthrough.png
│   ├── favicon.ico
│   ├── logo.svg
│   ├── notebook-example1.png
│   ├── notebook-example2.png
│   ├── notebook-example3.png
│   ├── notebook-example4.png
│   ├── notebook-example5.png
│   ├── notebook-example6.png
│   └── pdf-export.png
├── index.md
├── license.md
└── user-guide.md
```

**Comment by pawamoy** [comment]
Material for MkDocs sets margins (padding?) on HTML paragraphs, this is the vertical space you see. You can cancel it with some extra CSS, check out this page: https://pawamoy.github.io/mkdocstrings/handlers/python/#recommended-style-material.

Please re-open if it does not solve your issue, thanks!

**Comment by yanniskatsaros** [comment]
Worked beautifully, thank you for your quick response! Really appreciate this project.
