### ISSUE TITLE
Link to relative paths

### ISSUE THREAD

**Issue by Yajo** [pawamoy/mkdocstrings#144]
**Describe the bug**
When mkdocstrings produces cross-references to docs titles, it uses the full path starting from `site_url`. That setting cannot be changed dynamically. When you build several versions of your docs, at least one of them will always fail.

**To Reproduce**
1. Go to https://copier--254.org.readthedocs.build/en/254/api/reference/cli/#copier.cli.CopierApp and click on "skip_if_exists"
2. It takes you to https://copier.readthedocs.io/configuring/#skip_if_exists, which of course fails.

**Expected behavior**
It should take you to https://copier--254.org.readthedocs.build/en/254/configuring/#skip_if_exists instead.

**Screenshots**
![Peek 13-08-2020 12-45](https://user-images.githubusercontent.com/973709/90130740-dfd47e00-dd62-11ea-8e6b-9e53248c8ccb.gif)

**Information (please complete the following information):**
- OS: Linux
- Browser: Firefox
- `mkdocstrings` version: mkdocstrings==0.12.2

**Additional context**
That doc is built from https://github.com/copier-org/copier/pull/254 where you can see the full source code.

**Comment by pawamoy** [comment]
Hey @Yajo! Sorry it took so long for me to take a look at this. I finally have some time to work on my projects :slightly_smiling_face: 

So, this is clearly a bug, and I was never satisfied with using absolute URLs anyway. I'm going to rework the objects-URL mapping code to use relative links.

Thanks for the detailed report!

**Comment by pawamoy** [comment]
Fixed in 9c77f1f461fa87842ae39945f9521ee85b1e413b and version 0.13.1 is on its way :slightly_smiling_face:
