### ISSUE TITLE
Source code not displayed for properties.

### ISSUE THREAD

**Issue by mihasajko** [pawamoy/mkdocstrings#148]
Hi.

First of all, many thanks for this awesome package!

I was wondering whether it is intended that source code is not displayed for properties? 

I realize that properties are used as attributes, but they often implement some special logic. It would be very handy if one could examine the code in the generated docs.

- `mkdocstrings` version: [e.g. 0.10.2]

**Comment by pawamoy** [comment]
Hello @mihasajko, so sorry for answering so late, and thank you for the kind words!

As you can see I referenced this issue in pawamoy/pytkdocs#64, so it will be taken into account at some point :slightly_smiling_face:

**Comment by mihasajko** [comment]
Absolutely no worries, I've notice it's been take

**Comment by mihasajko** [comment]
Looking forward! :) PS: I've accidentally closed this issue, but I guess it's not a problem since you'll be taking it into account in pytkdocs.
