### ISSUE TITLE
Refactor tasks.py

### ISSUE THREAD

**Issue by RDIL** [pawamoy/mkdocstrings#150]
Hey,

So I noticed the tasks.py file, and I can't help noticing this reminds me of a long way to do a tool that I once saw that works quite well, called [Nox](https://nox.thea.codes).  I think that it could greatly simplify it, so just putting it out there.

**Comment by StephenBrown2** [comment]
Nox actually references Invoke in it's docs under ["Other Useful Projects"](url):
> [Invoke](https://www.pyinvoke.org/) is a general-purpose task execution library, similar to Make. Nox can be thought of as if Invoke were tailored specifically to Python testing, so Invoke is a great choice for scripts that need to encompass far more than Nox’s specialization.

So while Invoke and Nox both provide similar functionality, Invoke is more general, while Nox is more specialized.

Personally I am a fan of Nox, but if @pawamoy is more familiar with Invoke, I don't see much reason to switch. However, he may be open to a PR, if it would actually be more maintainable as a `noxfile.py` rather than `tasks.py`.

**Comment by pawamoy** [comment]
I actually tried nox, and I agree that it's a great tool. It seems well-maintained, it has great documentation, and noxfiles are a pleasure to read. Compared to it, invoke feels a bit old, not so well-maintained, and misses some functionality for Python. But there are a few things that led me to choose invoke over nox (at least for a small amount of time, to experiment with it a bit):

- nox creates virtualenvs for each session. I know the benefits, but in my opinion, it also has disadvantages: it generates lots of files. IDEs can choke on so many files. These venvs are created in the repo folder, so when you maintain lots of projects the venvs are scattered across all these projects (a matter of preference I guess).
- nox makes you define dependencies and install them in the noxfile. It creates redundancy with the dependencies in pyproject.toml. I guess this could be improved with [such a trick](https://github.com/python-poetry/poetry/issues/1644#issuecomment-688256688), if there's a way to tell nox to install the current package with specific extras.
- I wasn't sure if I could run arbitrary commands like with invoke, mainly `bash`, `rm`, `find` and such (which, I know, are not really cross-platform, but one thing at a time :p). I don't think I can run a command in a pseudo-terminal like invoke allows to do with `pty=True`.
- with nox I'm not really in control of the ouput

But now that you raised that issue, I looked at nox again, and I think some of these points can be solved. There are obvious benefits to using nox as well, like `@nox.parametrize` to test against multiple versions of multiple dependencies, and the native support for testing against different Python versions (that I had to reimplement myself for invoke).

So, in the end I'd be open to a PR replacing invoke with nox. Or you coulod simply help me solve these pain points I mentioned above, and I'll try to migrate myself :slightly_smiling_face: I think I'll give it a second try anyway, seeing how complicated my `tasks` become :sweat_smile:

**Comment by pawamoy** [comment]
I tried nox and in the end I don't really like it. It's painfully slow. I run checks and tests really often and I need it to be fast. Of course I can use the options to re-use the virtualenvs, or even not create them at all, but then there's no point in using nox over invoke I think :confused:. It's also *very* verbose, when I prefer a single sentence with a check mark if it passes or a cross if it doesn't.

Anyway, I really simplified the `tasks.py` with this commit: 645ca24. I remove the Python versions logic from it, and put it outside, in simple shell scripts. These scripts are optional: contributors can run tasks with `make TASK` if they fancy it (it has some advantages), or directly with `poetry run invoke TASK` (or even `invoke TASK` if they are in `poetry shell`).

The task are actually written in Python (to be somewhat cross-platform), and this was my main requirement, so I'm satisfied with this setup :slightly_smiling_face:
