### ISSUE TITLE
Support async function/methods

### ISSUE THREAD

**Issue by art049** [pawamoy/mkdocstrings#151]
Hi, thanks for the project !

Currently with the python handler it seems that we can't differentiate whether functions are "regular" or async.

I think it would be great to bring the async keyword in the "properties" field of the method.

I'm eager to implement this if you think it's worth @pawamoy .

**Comment by pawamoy** [comment]
Hey @art049, thanks!

Yes I totally agree to add support for coroutines properties :)

It shouldn't be hard to implement, inspect has a `iscoroutine` method I think. It must be done in the pytkdocs repo though :)

Don't pay attention to the quality checks if you start developing, just make sure the tests pass with `make test` :)

**Comment by art049** [comment]
Hello @pawamoy thanks for the merge on pytkdocs !
I tried to locally build the package and to use it with mkdocstrings but it seems like something is missing. The `async` property is never added.

Do you think another PR might be required ?

**Comment by pawamoy** [comment]
Hmm, I checked, and the changes you did are enough. When I try locally in pytkdocs own repo, it's working fine: 
![Screenshot_2020-09-19_14-39-40](https://user-images.githubusercontent.com/3999221/93667431-18fcbe00-fa86-11ea-8aaa-5f0081c39fab.png)

How did you install the package? `pip install ../pytkdocs` or something?

**Comment by art049** [comment]
Yes actually i ran `poetry build` and installed the new wheel directly in my repository that already uses  mkdocstring.

**Comment by art049** [comment]
Okay, i figured it out; I was still using my fork to build the wheel and for some reason the property didn't appear.
It works fine now, thanks !

**Comment by pawamoy** [comment]
Great! I'll try to release a new version of pytkdocs soon then :slightly_smiling_face:
