### ISSUE TITLE
Fix insertion of module docstring to mkdocs

### ISSUE THREAD

**Issue by timvink** [pawamoy/mkdocstrings#152]
inserting a module docstring looks really nice, f.e. on:

https://pawamoy.github.io/mkdocstrings/reference/plugin/

![image](https://user-images.githubusercontent.com/5570380/94011383-8f136480-fda7-11ea-9d4c-7f866dc76ca6.png)

However it also inserts a toc item for the module:

![image](https://user-images.githubusercontent.com/5570380/94011470-b2d6aa80-fda7-11ea-8379-596f73700f79.png)

Click on it, and scroll back to the top of the page:

![image](https://user-images.githubusercontent.com/5570380/94011508-c2ee8a00-fda7-11ea-84a4-85ac950956bd.png)

Minor issue, just letting you know in case you're not aware.

**Comment by pawamoy** [comment]
I am in fact aware, and it's tracked in #60.

Still, thank you very much for the report, I appreciate it! 

My CSS skills are not that high, so if you want to take a look at what happens here, it would be great!

I'll close this as duplicate :slightly_smiling_face:

**Comment by timvink** [comment]
Ah, I missed that one when scanning the issues.

Thanks for the great plugin!
