### ISSUE TITLE
Code indentation

### ISSUE THREAD

**Issue by GJBoth** [pawamoy/mkdocstrings#158]
Hi, I'm running into an issue with code indentation in my API. In the mkdocstrings API page (i.e. https://pawamoy.github.io/mkdocstrings/reference/handlers/python/) class methods are indented, which makes the API very readable. However, in our setup that doesn't happen, so all code is on the same indentation level. This makes the reference very unclear. I couldn't find any info on how to enable this, and using your mkdocs.yml file didnt help either (e.g. enabling tabs, superfences plugins). Which setting do I need to change? Or is this a material theme issue/option?

Thanks!

**Comment by pawamoy** [comment]
It's right here: https://pawamoy.github.io/mkdocstrings/handlers/python/#recommended-style-material!

Just some extra CSS, added in `mkdocs.yml`:

```yaml
extra_css:
  - css/mkdocstrings.css
```

I think it answers your question so I'll close this :slightly_smiling_face: 
Feel free to reopen or create a new issue if you encounter other problems!

**Comment by GJBoth** [comment]
Thanks, that indeed solves it! I saw the CSS but completely missed the indentation part :-)

**Comment by thatguysimon** [comment]
Just had the same issue.
The link above is no longer available, this is the correct link: https://mkdocstrings.github.io/python/customization/#recommended-style-material

@pawamoy Any way to get this CSS enabled by default out of the box? 🤔

**Comment by pawamoy** [comment]
Can you open a new issue @thatguysimon? Thanks!

**Comment by thatguysimon** [comment]
@pawamoy Sure, opened https://github.com/mkdocstrings/mkdocstrings/issues/551
