### ISSUE TITLE
Support for other python docstring styles

### ISSUE THREAD

**Issue by jnoortheen** [pawamoy/mkdocstrings#176]
**Is your feature request related to a problem? Please describe.**
It will be great if other standard docstring formats like `Numpy` and `RST` supported out of the box. 

**Describe the solution you'd like**
This is fairly trivial. There are libs out there like https://github.com/rr-/docstring_parser to help parse functions.

**Comment by pawamoy** [comment]
Feature request for Numpy format: https://github.com/pawamoy/pytkdocs/issues/7
Pull request for RST format: https://github.com/pawamoy/pytkdocs/pull/71

RST will never be fully supported, see the discussion in the mentioned above.

Also, I had https://github.com/rr-/docstring_parser in my radar, unfortunately we do a bit more in the pytkdocs parsers: we use type annotations to populate the types of the documented attributes/arguments in docstrings, which the linked project does not do. But if you want to open a PR on pytkdocs for the Numpy format using this lib, I could review it :slightly_smiling_face: 

Leaving this issue open for visibility!

**Comment by jnoortheen** [comment]
Oh I haven't checked that repo. I don't have much time lately. I converted my code to use google docstrings :) Since there are people working on it, feel free to close this issue.

**Comment by pawamoy** [comment]
Since the RST PR was merged and there's an issue for the Numpy format in pytkdocs, I'll close this one.
