### ISSUE TITLE
Keep newline of docstrings?

### ISSUE THREAD

**Issue by TensorTom** [pawamoy/mkdocstrings#182]
Possible to parse newline in docstrings and keep them?

**Comment by pawamoy** [comment]
Hello! Newlines should definitely be kept. Do you have an example where a newline is not kept?

**Comment by pawamoy** [comment]
Hey again, I'll close this but feel free to open a new issue with more details!

**Comment by justinTM** [comment]
https://github.com/mkdocstrings/mkdocstrings/issues/315
