### ISSUE TITLE
Incorporate the recommended CSS style in the package

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/mkdocstrings#189]
**Is your feature request related to a problem? Please describe.**
It's a bit annoying to copy over the recommended CSS in every project. Also asked here: https://github.com/pawamoy/mkdocstrings/pull/159#pullrequestreview-506099310

**Describe the solution you'd like**
We can package the recommended stylesheets.
The question is: how to use them in the MkDocs `extra_css` option.

**Comment by oprypin** [comment]
I think I'm gonna withdraw this request. I'm also [giving](https://oprypin.github.io/mkdocstrings-crystal/styling.html) users the freedom to put whatever styles they want, and it also works OK without any styles

especially after the removal of `.hidden-toc` in https://github.com/pawamoy/mkdocstrings/pull/209/files

**Comment by pawamoy** [comment]
Noted. Could still be nice to have an opt-in bundled CSS file :slightly_smiling_face:

**Comment by oprypin** [comment]
FWIW I know how a plugin could add its files into the site.

`on_files`: add a file with a chosen arbitrary name.
`on_config`: insert that file name into `extra_css`.
