### ISSUE TITLE
Markdown headings can bust to the topmost nav level

### ISSUE THREAD

**Issue by oprypin** [pawamoy/mkdocstrings#192]
I'm actually not entirely sure if it's the case for Python renderer, but in my own renderer I ran into the issue that if the docstring contains a `# Markdown Heading`, it's not adjusted according to the current `heading_level`, so in the nav it'll just appear as a topmost item regardless of what's happening around it.

I'm currently looking into a solution.

**Comment by oprypin** [comment]
For myself I fixed it in https://github.com/oprypin/mkdocstrings-crystal/commit/d621b1264108ea742bfa6a6e528b31b3f25af521

|Before|After|
|-|-|
|![Before](https://user-images.githubusercontent.com/371383/101421187-10cd5580-38f4-11eb-9ff5-0afd4f20f02c.png)|![After](https://user-images.githubusercontent.com/371383/101421476-a4068b00-38f4-11eb-8268-d37744c8a90d.png)|

**Comment by pawamoy** [comment]
It certainly behaves the same for the Python renderer. I didn't think about using headings in docstrings myself.
If you want to send a PR with your fix @oprypin, I'll accept it!
