### ISSUE TITLE
Clarity on exactly which docstring styles are supported?

### ISSUE THREAD

**Issue by connerxyz** [pawamoy/mkdocstrings#214]
It's not clear exactly which docstrings are supported. Hoping to clear that up.

What I've gathered below, is this correct?

- Markdown: Yes.
- Google: Yes.
- Numpy: No.
- ReST: Sort of.

So docstring parsing is delegated to `pytkdocs`, which supports Google, and some limited ReST.

Referring to `pytkdocs` where they state "1: reStructured Text parsing is in active development and is not feature complete yet."

**Comment by oprypin** [comment]
Your summary seems correct

**Comment by pawamoy** [comment]
Hello @connerxyz, sorry for the confusing docs :slightly_smiling_face: 

![Screenshot_2021-01-12_19-21-28](https://user-images.githubusercontent.com/3999221/104355822-82a84880-550b-11eb-9593-16e444b528fc.png)

![Screenshot_2021-01-12_19-21-54](https://user-images.githubusercontent.com/3999221/104355834-863bcf80-550b-11eb-9893-c6192a1dff1d.png)

I think it states pretty clearly what we support (google-style and restructuredtext **style**), but we could emphasize restructuredtext is only partially supported, as a style and not a whole markup (mkdocstrings converts markdown only, nothing else, so rest markup will be converted as if it was markdown as well).

There's also a PR for Numpy style pending on pytkdocs :slightly_smiling_face: 
Docs will be updated when/if it's merged of course
