### ISSUE TITLE
Attribute docstring not dedented

### ISSUE THREAD

**Issue by Yajo** [pawamoy/mkdocstrings#225]
**Describe the bug**
Multiline attribute docstring does not get dedented properly.

**To Reproduce**

```py
@dataclass
class Worker:
    """Copier process state manager.

    This class represents the state of a copier work, and contains methods to
    actually produce the desired work.

    To use it properly, instantiate it by filling properly all dataclass fields.

    Then, execute one of its main methods, which are prefixed with `run_`:

    -   [run_copy][copier.main.Worker.run_copy] to copy a subproject.
    -   [run_update][copier.main.Worker.run_update] to update a subproject.
    -   [run_auto][copier.main.Worker.run_auto] to let it choose whether you
        want to copy or update the subproject.
    """

    src_path: Optional[str] = None
    """String that can be resolved to a template path, be it local or remote.

    See [Template.url][copier.main.Template.url] for more details.

    If it is `None`, then it means that you are [updating a
    project](updating.md), and the original `src_path` will be obtained from
    [the answers file](configuring.md#the-answers-file)
    """
```

**Expected behavior**
![screenshot-2021-02-06-08-07-01](https://user-images.githubusercontent.com/973709/107112809-55249580-6852-11eb-8277-968da8d32ba9.png)

**Actual behavior**

2nd and later lines of `src_path` docstring become code blocks:

![imagen](https://user-images.githubusercontent.com/973709/107112819-65d50b80-6852-11eb-9e96-44d8b1d3b138.png)

**Information (please complete the following information):**
- OS: Linux
- Browser: Firefox
- `mkdocstrings` version: bf217e6

**Additional context**
While developing https://github.com/copier-org/copier/pull/314 (code not yet pushed).

**Comment by pawamoy** [comment]
Thanks @Yajo, good catch! It's surely because we're using a `textwrap.dedent` somewhere instead of `inspect.getdoc`/`inspect.cleandoc`. I'll investigate :slightly_smiling_face:

**Comment by pawamoy** [comment]
Pushed a fix, will release it soon, closing!
