### ISSUE TITLE
Lost cross-references from normal docs to python docstrings?

### ISSUE THREAD

**Issue by Yajo** [pawamoy/mkdocstrings#226]
**Describe the bug**
As you know I'm under a big refactor on https://github.com/copier-org/copier/pull/314. However, right now I'm trying to document it while it's fresh, and I'm getting warnings where they weren't before.

**To Reproduce**
1. Clone https://github.com/copier-org/copier/pull/314/commits/5ee86665cb03bca7630437e673606bec0dee0bc4
2. `poetry install`
3. `poetry run mkdocs serve`
4.  There's plenty of errors I'm currently reviewing, but this one is **not** an error AFAICS:

        WARNING -  reference/cli.md: Could not find cross-reference target '[answers_file]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[exclude]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[vcs_ref]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[pretend]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[force]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[skip_if_exists]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[use_prereleases]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[quiet]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[data]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[cleanup_on_error]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[copier.main.copy]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[copier.main.copy]' 
        WARNING -  reference/cli.md: Could not find cross-reference target '[the-copier-answersyml-file]' 

    The file `reference/cli.md` is a bit misleading because the problem is really on `copier/cli.py`, specifically [here](https://github.com/copier-org/copier/blob/5ee86665cb03bca7630437e673606bec0dee0bc4/copier/cli.py#L53-L60). Those lines didn't change, and they were relying on automatic resolution of cross-references from [this docs file downwards](https://github.com/copier-org/copier/blob/5ee86665cb03bca7630437e673606bec0dee0bc4/docs/configuring.md#answers_file). For some reason, those cross-references no longer resolve. 🤷🏼‍♂️ 

**Expected behavior**
Cross-references from markdown docs to python docstrings should be automatically resolved.

**Screenshots**
From https://copier.readthedocs.io/en/stable/api/reference/cli/#copier.cli.CopierApp:
![imagen](https://user-images.githubusercontent.com/973709/107274915-fb39f080-6a48-11eb-8c71-0d0f95665ded.png)

From https://copier--314.org.readthedocs.build/en/314/reference/cli/#copier.cli.CopierApp:
![screenshot-2021-02-08-20-05-39](https://user-images.githubusercontent.com/973709/107274969-11e04780-6a49-11eb-91b9-e55f93799dfb.png)

**Information (please complete the following information):**
- OS: Linux
- Browser: Firefox
- `mkdocstrings` version: bf217e66c3b459781100d53c2a048272260b355c (from git to fix some other issues... you know).

**Comment by oprypin** [comment]
Sorry @Yajo that this is not documented yet, but it's expected as per https://github.com/pawamoy/mkdocstrings/pull/220. You just need to add `- autorefs` into `plugins:`, in addition to `- mkdocstrings`.

**Comment by Yajo** [comment]
Oh thanks!!!

**Comment by pawamoy** [comment]
Thanks @oprypin for answering :slightly_smiling_face: 
Closing! We'll document this in the changelog for the next version of course
