### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by bennylp** [pawamoy/mkdocstrings#42]
On Windows, `mkdocs serve`  fails with the following exception:

```
ERROR   -  Error reading page 'api\dataset\config.md': list index out of range
Traceback (most recent call last):
  File "c:\users\bennylp\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
...
  File "c:\users\bennylp\appdata\local\programs\python\python37\lib\site-packages\mkdocstrings\renderer.py", line 50, in render_object
    lines.append(f'\n??? note "Show source code in {obj.relative_file_path}"')
  File "c:\users\bennylp\appdata\local\programs\python\python37\lib\site-packages\mkdocstrings\documenter.py", line 190, in relative_file_path
    while path_parts[-1] != file_path_parts[-1]:
IndexError: list index out of range
```

I think the reason is because the codes in `documenter.py` does path splitting by '/' character, and this fails on Windows because on Windows the path separator is '\\'. 

I did a quick and dirty fix by replacing '\\' with '/' on all path strings in `documenter.py`, and I think it works (at least `mkdocs serve` is serving), but the right solution is to use `os.path` functions I think.

**Comment by pawamoy** [comment]
Ah yes, I met this before but didn't push a fix yet. Will do asap

**Comment by ofek** [comment]
Is this fixed?

**Comment by pawamoy** [comment]
I'll dedicate a few hours this week-end to work on mkdocstrings so hopefully it will be fixed for next week :slightly_smiling_face:

**Comment by pawamoy** [comment]
Just pushed a fix in 70f9af5. Could someone try it on Windows?

**Comment by bennylp** [comment]
I just tested it and it works. Thanks!

**Comment by pawamoy** [comment]
Great, will release version 0.7.1 then :slightly_smiling_face:
