### ISSUE TITLE
Support for (markdown-)katex for rendering latex

### ISSUE THREAD

**Issue by spoorendonk** [pawamoy/mkdocstrings#46]
I am using https://gitlab.com/mbarkhau/markdown-katex to render latex in the markdown files.
It would be nice to be able to include latex in the docstrings and render them.

It does seem to work for some inline latex like ``$`\lambda`$`` but not for the multi-line environment like

````
```math
f(x) = \int_{-\infty}^\infty
\hat f(\xi)\,e^{2 \pi i \xi x}
\,d\xi
```
````

**Comment by pawamoy** [comment]
If you included your markdown extension in mkdocs config, it should work as expected, though maybe some extensions are conflicting.

We currently add these extensions for pages containing autodoc instructions:
- admonition
- codehilite with guess_lang=False
- attr_list
- pymdownx.details
- pymdownx.superfences
- pymdownx.inlinehilite
- toc with permalink=True

Is latex rendered correctly in pages **not** containing autodoc instructions?

**Comment by spoorendonk** [comment]
I have

```
markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
```

The multi-line example above renders correctly in .md files. The inline version is OK in both .py and .md files

**Comment by pawamoy** [comment]
Do you have a repo I can clone to try and replicate locally?

**Comment by spoorendonk** [comment]
https://github.com/spoorendonk/mkdocstrings-katex

I found that it is because the parsing of python escape characters in the latex code, like `\x`.
A workaround is to escape all such stuff in the docstrings, so `\x` becomes `\\x` and also latex line breaks `\\` should be `\\\\`.

I am not sure how to overcome this? Or if the escaping is the solution.

**Comment by pawamoy** [comment]
It makes sense. Try using r-strings for docstrings containing LaTeX markup:

```
def func():
    r"""My docstring which is __not__ escaped!"""
```

**Comment by pawamoy** [comment]
I'm closing since it's not related to mkdocstrings itself.
