### ISSUE TITLE
Issue with wrapper functions

### ISSUE THREAD

**Issue by HuiiBuh** [pawamoy/mkdocstrings#48]
Hey

I have an issue with wrapper functions. Instead of the function that should be documented the wrapper gets displayed in the code preview.  
In addition the Notes, Params, ... do not get displayed.

Code:
![image](https://user-images.githubusercontent.com/46561026/75286190-5662db00-5818-11ea-9881-f38f3067faf6.png)

Docs:
![image](https://user-images.githubusercontent.com/46561026/75286236-75fa0380-5818-11ea-907f-4f1889236854.png)

**Comment by pawamoy** [comment]
Hey, thanks for the report!

I think it's really complicated to handle this in `mkdocstrings`. However, from this [SO post](https://stackoverflow.com/questions/30799700/function-name-of-wrapped-function), it seems you can simply add `@functools.wraps(function)` just above your `async def wrapper(*args, **kwargs)` line.

I just tried with and without `functools.wraps`: without and you get the wrapper code and docstring, with and everything seems to work fine!

**Comment by HuiiBuh** [comment]
Thanks for the quick reply. 
Your suggestion is working correctly. 
![image](https://user-images.githubusercontent.com/46561026/75288589-f3c00e00-581c-11ea-87a1-8fa07d79fa41.png)

**Comment by pawamoy** [comment]
Ah sorry, the code I mentioned is not yours actually. Maybe you have no control over the `get_url` wrapper either. If you can, try to wrap using `functools.wraps`, otherwise we'll think of something else.
