### ISSUE TITLE
Nested Classes

### ISSUE THREAD

**Issue by HuiiBuh** [pawamoy/mkdocstrings#49]
Currently nested classes are note supported my mkdocstrings.

![image](https://user-images.githubusercontent.com/46561026/75357835-4b5c8900-58b2-11ea-9c45-76930b0320db.png)

![image](https://user-images.githubusercontent.com/46561026/75357961-747d1980-58b2-11ea-8d4a-b362ca5d8931.png)

**Comment by pawamoy** [comment]
Thanks again for the report @HuiiBuh :slightly_smiling_face: 

Indeed, in `get_class_documentation`, I forgot to handle the case where a class is a member of another class, i.e. not directly defined in the module's contents.

For attributes of a nested class, code was missing as well before dispatching the attributes. I was able to fix it locally, will push so you can try it.

**Comment by pawamoy** [comment]
See 7fef903

**Comment by StephenBrown2** [comment]
What if we want to exclude nested classes?

**Comment by pawamoy** [comment]
It is not very practical but you can already use the global filters to exclude the names of your nested classes. Later we'll have complete options to select/unselect objects globally or per autodoc instructions.

**Comment by pawamoy** [comment]
Continuing over here: https://github.com/pawamoy/py-tkdocs/issues/4
