### ISSUE TITLE
Allow configurable top heading level

### ISSUE THREAD

**Issue by StephenBrown2** [pawamoy/mkdocstrings#5]
Currently my interface documentation has a primary class, with subclasses created as attributes on init. In order to document them logically, I've organized the `api.md` as:

```markdown
# MainClass

::: library.MainClass

## MainClass.sub_class_a

::: library.package.module.SubClassA

## MainClass.sub_class_b

::: library.package.module.SubClassB
```

However, the header value is only 1 or two, dependent on "show_top_level_heading": https://github.com/pawamoy/mkdocstrings/blob/28f0e4279966ff14b2c4e96adc8a6753acc03e20/src/mkdocstrings/plugin.py#L93

I would like to set it to `3`, perhaps with a `start_heading_level` config option. This and the other config options should be exposed to the user, but that will probably come later as this project matures.

**Comment by pawamoy** [comment]
Yep, this is planned!

I have written a few TODOs at the top of `plugin.py`, and the initial heading level is one of them. I plan on making all the options in the `config` dictionary available below the `::: dotted.path` instructions, just like what `mkautodoc` is doing. Something like:

```markdown
::: my.lib
    :initial_heading_level: 3
```

**Comment by pawamoy** [comment]
This is implemented in the new version 0.9.1:

```
::: my.lib
    rendering:
      heading_level: 3
```

Check out the rendering options of the Python handler: https://pawamoy.github.io/mkdocstrings/reference/handlers/python/#mkdocstrings.handlers.python.PythonRenderer.DEFAULT_CONFIG

**Comment by pawamoy** [comment]
I'll close this issue, if you have any problem with the new version, open new issues :slightly_smiling_face:

**Comment by StephenBrown2** [comment]
yay config! 🎉
