### ISSUE TITLE
Make templates overridable

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/mkdocstrings#59]

**Comment by Holt59** [comment]
I have a working version for this using a plugin configuration `custom_templates` (similar to `custom_dir` for `theme`):

```
plugins:
  - mkdocstrings:
      custom_templates: "./docs/custom_templates"
```

And then within `custom_templates`, I follow the structure you use, e.g., `python/material`.

Currently, the renderer will throw `ThemeNotSupported` even if the custom template folder contains everything needed so I am not sure how to handle that... Maybe not throw the exception? In my opinion, a warning should be sufficient since the renderer will fail later by not finding the require template.

Let me know your thoughts on this so that I can do the proper changes and then make a PR!

**Comment by pawamoy** [comment]
Thank you for your interest and contribution @Holt59!

I think the best thing to do would be to pass the root of the templates folder to the jinja env's file system loader, and indeed let the renderer fail later (and catch potential exceptions to issue errors or warnings).

https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.FileSystemLoader

So instead of the whole

```python
        themes_dir = Path(__file__).parent.parent / "templates" / directory
        theme_dir = themes_dir / theme
        if not theme_dir.exists():
            if self.FALLBACK_THEME != "":
                log.warning(
                    f"mkdocstrings.handlers: No '{theme}' theme in '{directory}', "
                    f"falling back to theme '{self.FALLBACK_THEME}'"
                )
                theme_dir = themes_dir / self.FALLBACK_THEME
            else:
                raise ThemeNotSupported(theme)

        self.env = Environment(autoescape=True, loader=FileSystemLoader(str(theme_dir)))
```

...we could simply do

```python
        templates_dir = str(Path(__file__).parent.parent / "templates")
        self.env = Environment(autoescape=True, loader=FileSystemLoader(templates_dir))
```

With this change, we would need to refactor the current material templates to use

```
{% include "python/material/class.html" %}
```

instead of

```
{% include "class.html" %}
```

But this change would also allow to override templates very easily!

If the user defines a `custom_templates` key in the plugin config, we can simply pass it to the jinja loader:

```python
        templates_dir = str(Path(__file__).parent.parent / "templates")
        self.env = Environment(
            autoescape=True,
            loader=FileSystemLoader([CUSTOM_TEMPLATES_PATH, templates_dir])
        )
```

...then the custom templates will be used first if they exist :slightly_smiling_face: 

Another benefit could be that a template can access templates from other handler/themes. A use-case would be to have a common template that is reused across several themes, to avoid duplication in each theme.


Finally, since the loader will contain a lot of templates, there are some options that we should maybe disable on the loader/env, such as `optimized` or `auto_reload` (see https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment). I'm not sure what `optimized` is doing, but what I know is that we *must not* read and validate every template syntax just to render a few. Specifically, we do not want [compile_templates](https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment.compile_templates) or similar to be executed.

What do you think?

**Comment by pawamoy** [comment]
So I looked at your fork, and I like what you did. You can indeed remove the exception raising in the renderer's `__init__` constructor, and catch `jinja2.TemplateNotFound` in the extension's `run` method to issue a proper error and abort.

The question is: do we put the whole templates folder into the jinja loader (what I proposed above), or do we keep on putting just the theme directories into it. Waiting for your feedback :slightly_smiling_face:

**Comment by Holt59** [comment]
I am trying to work something out around your idea of having the `FileSystemLoader` use the root of the template folder instead of the `python/material` one. 

One issue I have is with the fallback theme. Assuming I call `self.env.get_template(f"python.{self.theme}.{data['category']}.html")` in `render()` (after setting `theme` in `BaseRenderer`), this will fail even if the fallback theme contain the appropriate templates.

**Comment by pawamoy** [comment]
What do you mean by it will fail? Don't hesitate to open a PR prefixed with WIP (work in progress) so we can comment on the code.

**Comment by Holt59** [comment]
I mean that if I want to get `python.mytheme.parameters`, and this one does not exist, it will not fallback to `python.material.parameters` as it does now.

**Comment by pawamoy** [comment]
I still do not understand :sweat_smile: 

Lets take an example.

- You override the material theme with a set of templates in `docs/custom/python/material`.
- One of these templates has `{% include "parameters.html" %}` in it.

- Case 1: `parameters.html` exists in your custom theme. Therefore it is used.
- Case 2: `parameters.html` does not exist in your custom theme. The next found `parameters.html` template is the one from the material theme, which seems to be the correct behavior.


Another example.

In `mkdocs.yml`, you are using a theme with is not supported by `mkdocstrings` yet, e.g. `readthedocs`.

So, taking previous contents again:

- Case 1: `parameters.html` exists in your custom theme. Therefore it is used.
- Case 2: `parameters.html` does not exist in your custom theme. The next found `parameters.html` template is the one from the fallback theme (which is material), because there is no `readthedocs` theme for `mkdocstrings`'s Python handler.


Is there something bothering you in this behavior?

**Comment by pawamoy** [comment]
Maybe I understand:

> I mean that if I want to get python.mytheme.parameters, and this one does not exist, it will not fallback to python.material.parameters as it does now.

But you're not supposed to override a theme that does not exist :confused: 
If you want to fallback onto the material theme, you should override the material templates, and not create a custom `mytheme` directory. Did I get it right?

**Comment by Holt59** [comment]
I was referring to the case were the file loader points to the root. So instead of `{% include "parameters.html" %}` you get `{% include "python/material/parameters.html" %}`. It's not problematic in the template themselves I think, because you should not include something you don't provide, but only when fetching the initial template from python.

**Comment by pawamoy** [comment]
Pffffew, I finally got it, sorry it took so long :tired_face: 

Indeed, if you are using the `readthedocs` theme of `mkdocs`, and create a custom `readthedocs` theme, then if you override just some of the templates, the ones that are not overrode will not fallback to the fallback theme since the fallback theme is `python/material/something.html` and not `python/readthedocs/something.html`.

Is this problematic? Not sure. If one creates a custom theme to support a native mkdocs theme outside of what mkdocstrings supports, I guess one should simply open a PR to add this custom theme to mkdocstrings.

Anyway. Let's drop this option of adding the roots to the loader, and keep the current behavior as it seems to be simpler.

I'll continue the discussion on your PR :slightly_smiling_face:

**Comment by pawamoy** [comment]
Done in #82
