### ISSUE TITLE
Missing depandcies: pymdown-extensions, mkdocs-material

### ISSUE THREAD

**Issue by Mattwmaster58** [pawamoy/mkdocstrings#66]
cloning the repo and installing with `pip install mkdocstrings` works, but as soon as `mkdocs serve` is run, the two aforementioned packages are nowhere to be found. Am I missing something?

**Comment by pawamoy** [comment]
Well, `mkdocstrings` is not supposed to depend on any theme. Currently it only supports the Material for MkDocs theme, but it's only that: support. Maybe we could add `mkdocs-material` as a dependency, but later it should be removed when more themes are supported (especially the native ones), and it could be quite confusing for users :confused: 

Right now I think it's best to warn users that they must Material for MkDocs themselves. I'll update the README and docs. What do you think?

**Comment by Mattwmaster58** [comment]
If I'm understanding the problem correctly something like this should suffice:

> Note: this project currently only works with the Material theme of MkDocs at this time. Therefore, it is required that you have it installed.

**Comment by Mattwmaster58** [comment]
And with regard to `pymdownx`, I assume that's this project is missing that dependency?

**Comment by pawamoy** [comment]
`pymdownx` is a dependency of `mkdocs-material`, and I don't believe we're doing anything in `mkdocstrings` that would require it as well.

**Comment by pawamoy** [comment]
Hmm in fact yes, we depend on pymdownx for the `highlight` jinja filter. I'll add it as a dependency. Thanks @Mattwmaster58
