### ISSUE TITLE
Functions with `*` (Keyword-Only Arguments) notation render `*` between each arg

### ISSUE THREAD

**Issue by StephenBrown2** [pawamoy/mkdocstrings#68]
https://www.python.org/dev/peps/pep-3102/ allows for a `*` to delineate the following arguments as keyword-only, meaning they cannot be called positionally, even if they have no default value.

However, with mkdocstrings/pytkdocs, it seems the star is added between each argument. e.g.:

```py
async def get_exceptions(
    self, *, calendar_id: int, start_date: pendulum.Date, end_date: pendulum.Date
) -> typing.Dict:
```

renders as

<img width="656" alt="Screenshot 2020-03-30 at 10 00 38" src="https://user-images.githubusercontent.com/1148665/77934476-603f8a00-726d-11ea-9f7e-471828ca3181.png">

Feel free to move this issue to pytkdocs if it's more suited to be there.

**Comment by pawamoy** [comment]
No no it's a rendering issue, it's in the right place :slightly_smiling_face: 

The `signature.html` template must be fixed!

**Comment by pawamoy** [comment]
Seems to be a problem of scope with Jinja2.

With `items = [0, 1, 2]`:
```
{% set v = True %}
{% set w = True %}
{% for item in items %}
    {% if w %}
        {% set w = False %}
    {% endif %}
    {{ item }}, v={{ v }}, w={{ w }}
    {% if v %}
        {% set v = False %}
    {% endif %}
{% endfor %}
```

...rendered template is

```

**Comment by pawamoy** [comment]
It can be fixed with a namespace:

```
{% set ns = namespace(v = True) %}
{% for item in items %}
    {{ item }}, v={{ ns.v }}
    {% if ns.v %}
        {% set ns.v = False %}
    {% endif %}
{% endfor %}
```

```
    0, v=True
    1, v=False
    2, v=False
```

I'll update the template!
