### ISSUE TITLE
Decorated functions ignored

### ISSUE THREAD

**Issue by gegnew** [pawamoy/mkdocstrings#73]
This is similar to a topic [documented](https://github.com/pawamoy/mkdocstrings/blob/336421af95d752671276c2e88c5c173bff4093cc/docs/troubleshooting.md#my-wrapped-function-shows-documentationcode-for-its-wrapper-instead-of-its-own) in your troubleshooting guide, but not precisely. In this case, I'm using the Python builtin `@[property_name].setter` decorator to set a property, but this docstring is ignored by `mkdocstrings`. In fact, that property of the class I am documenting is not registered at all, even when explicitly selected with 
```
    selection:
      members:
        - property_name
```

EDIT: This property will show up like 
**property_name** _property writable_ 
with no docstring if I set       `show_if_no_docstring: true`

I would be happy to try to fix this, if you can point me in the right direction.

Thanks!

**Comment by gegnew** [comment]
Argh, scratch that, I had the docstring set on the setter, not the getter

**Comment by pawamoy** [comment]
I was thinking, maybe we could merge the setter docstring into the getter one. I'll people comment on this or upvote.
