### ISSUE TITLE
0.10.1 won't install with latest pymdown-extensions

### ISSUE THREAD

**Issue by ofek** [pawamoy/mkdocstrings#74]
We've been using the latest releases https://github.com/squidfunk/mkdocs-material/issues/1498

```
mkdocs-material>=5.0.0rc4
pymdown-extensions>=7.0b2
```

which should both release officially this week.

However, this pins using carets https://python-poetry.org/docs/dependency-specification/#caret-requirements

https://github.com/pawamoy/mkdocstrings/blob/09791898dea482e307e3fb16bb503843d5eac3ef/pyproject.toml#L25
https://github.com/pawamoy/mkdocstrings/blob/09791898dea482e307e3fb16bb503843d5eac3ef/pyproject.toml#L37

Let's increase the range

https://python-poetry.org/docs/dependency-specification/#multiple-requirements

**Comment by pawamoy** [comment]
If it works, sure, let's do that :)

Do you suggest `>= 6.3, < 8.0` and `>= 4.5, <6.0`?

**Comment by ofek** [comment]
Yup that will work!

**Comment by ofek** [comment]
https://facelessuser.github.io/pymdown-extensions/about/release/#upgrading-to-70
https://deploy-preview-1486--mkdocs-material-preview.netlify.com/releases/5/

**Comment by ofek** [comment]
They both were just released!

**Comment by pawamoy** [comment]
Alright, I'll publish a new release as well :slightly_smiling_face:

**Comment by pawamoy** [comment]
Released 0.10.2!
