### ISSUE TITLE
Docstrings of parent methods

### ISSUE THREAD

**Issue by jan-matthis** [pawamoy/mkdocstrings#78]
How would I render docstrings of methods inherited from a parent class?

To try this out, here is a minimal example for which I'd have expected `parent_method` to show up as part of the `test.Child` docstring:

```python
# test.py

class Parent:
    def parent_method(self, arg):
        """Parent method
        
        Args:
            arg: Arg
        """

class Child(Parent):
    def child_method(self, arg):
        """Child method
        
        Args:
            arg: Arg
        """
```

```markdown
# index.md

::: test.Child
    selection:
      members:
        - child_method
        - parent_method
```

**Comment by pawamoy** [comment]
Indeed inherited members are not picked up by `pytkdocs` right now. I wonder if we should pick them up by default and let the users filter the members, or if we should add another option like Sphinx's `inherited-members`.

**Comment by jan-matthis** [comment]
Thanks for the quick answer! Maybe it's good to have the extra flexibility of `inherited-members` to be able to apply separate filters on them (and show all without leading `_` by default)? Either way, this would be a highly useful feature.

**Comment by pawamoy** [comment]
So you're suggesting to simply copy the `members` configuration option as `inherited_members`, and make it accept the same possible values (true, false, or a list of names)?

**Comment by jan-matthis** [comment]
Yes, that's what I was thinking of

**Comment by pawamoy** [comment]
OK, it should be fairly easy to implement then. I'll open the corresponding feature request on `pytkdocs`.

**Comment by pawamoy** [comment]
Alright. I just released pytkdocs version 0.5.0. mkdocstrings does not yet accept it. I'll increase the version range soon. You will then be able to add a `inherited_members: true` to the `selection` options. The option only accepts a boolean, not a list of members, nor a list of filters: I wanted to do a simple pass first. If you all really need the ability to select or filter inherited members differently than direct members, we will open a new feature request.

**Comment by ofek** [comment]
Hmm, https://github.com/pawamoy/pytkdocs/issues/43

**Comment by pawamoy** [comment]
Closing! Open new issues if other problems arise :slightly_smiling_face:

**Comment by cgarciae** [comment]
Hey, I am not able to inherit documentation for `__init__`, is there are restriction regarding this method?

**Comment by pawamoy** [comment]
Oh, yeah, it happens here: https://github.com/pawamoy/pytkdocs/blob/master/src/pytkdocs/loader.py#L587-L600. I think we could safely remove this since we can now chose to inherit or not.

**Comment by cgarciae** [comment]
@pawamoy being able to inherit the docs of the `__init__` method would save me a lot of work. Is this a planed feature?

**Comment by cgarciae** [comment]
I think for the same reason, I also cant get the documentation for inherited class methods right now.

**Comment by pawamoy** [comment]
Yes, I'd consider the current behavior a bug. Could you open a new issue? Just a sentence and a link to your previous comment will do :) It's hard to keep track of things in comments.

Also, a PR is welcome, I'm too busy these days :/

Thanks!

**Comment by samsja** [comment]
I cannot make this work :confused: can someone explain how the `index.md` should look like for it to work ? Thanks in advance :raised_hands:

**Comment by pawamoy** [comment]
Hey @famura, yes indeed, this is not yet implemented. If you find a workaround let us know :slightly_smiling_face:

**Comment by famura** [comment]
OK, thank you for your super quick response
