### ISSUE TITLE
Add support for class attributes using Attributes keyword

### ISSUE THREAD

**Issue by iicky** [pawamoy/mkdocstrings#88]
**Is your feature request related to a problem? Please describe.**

The [Google Style Python Docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) guide allows for documenting class attributes using the `Attributes` keyword like this:

```
Attributes:
    module_level_variable1 (int): Module level variables may be documented in
        either the ``Attributes`` section of the module docstring, or in an
        inline docstring immediately following the variable.

        Either form is acceptable, but the two should not be mixed. Choose
        one convention to document module level variables and be consistent
        with it.
```

Currently it looks like `mkdocstrings` does not support this keyword for documentation.

**Describe the solution you'd like**

It would be awesome to be able to document class attributes using the `Attributes` keyword and to have it output in a nice table like the `Parameters` keyword does. The table would need to have the name, type, and description columns.

**Describe alternatives you've considered**

Right now, I am just using a markdown list to define the columns. It works, but isn't as slick.

**Additional context**

No additional context - keep up the good work, I'm digging the project.

**Comment by pawamoy** [comment]
Indeed, seems like a good idea :slightly_smiling_face:

**Comment by pawamoy** [comment]
Done in b56175f, will release soon
