### ISSUE TITLE
Collection error v0.11.0

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/mkdocstrings#91]
**Describe the bug**
Collection error due to JSON failing to load the file line read on stdout. I suspect the Python interpreter to pre-execute code that is writing to stdout, or simply writing some blank lines to stdout for some reason.

**To Reproduce**
Waiting for feedback in https://github.com/rdilweb/docs/commit/cc20660bcaad8cfa114e5d197cea8cd0925a0d19

**Expected behavior**
No collection error.

**Information (please complete the following information):**
- `mkdocstrings` version: 0.11.0

**Additional context**
Possible fix:

```diff
diff --git a/src/mkdocstrings/handlers/python.py b/src/mkdocstrings/handlers/python.py
index 88e8da3..c8127eb 100644
--- a/src/mkdocstrings/handlers/python.py
+++ b/src/mkdocstrings/handlers/python.py
@@ -125,13 +125,19 @@ class PythonCollector(BaseCollector):
         """
         log.debug("mkdocstrings.handlers.python: Opening 'pytkdocs' subprocess")
         env = os.environ.copy()
+        env["PYTHONUNBUFFERED"] = "1"
 
-        python_str = "; ".join(setup_commands) + "; " if setup_commands else ""
-        cmd = python_str + "from pytkdocs.cli import main; main(['--line-by-line'])"
+        if setup_commands:
+            cmd = [
+                "python",
+                "-c",
+                "; ".join(setup_commands) + "; from pytkdocs.cli import main; main(['--line-by-line'])"
+            ]
+        else:
+            cmd = ["pytkdocs", "--line-by-line"]
 
-        env["PYTHONUNBUFFERED"] = "1"
         self.process = Popen(  # noqa: S603,S607 (we trust the input, and we don't want to use the absolute path)
-            ["python", "-c", cmd], universal_newlines=True, stderr=PIPE, stdout=PIPE, stdin=PIPE, bufsize=-1, env=env,
+            cmd, universal_newlines=True, stderr=PIPE, stdout=PIPE, stdin=PIPE, bufsize=-1, env=env,
         )
 
     def collect(self, identifier: str, config: dict) -> Any:
```

Ping @RDIL @rossmechanic

**Comment by rossmechanic** [comment]
Hi @pawamoy , just tried this locally, and haven't been able to produce any errors (it has all been working perfectly, with or without setup_commands). However, I have a fix in order to get the print statements back to stdout. We can do the following to catch the stdout and flush it:
```
        catch_command_stdout ="from io import StringIO; import sys; sys.stdout = StringIO(); "
        reset_stdout = "sys.stdout.flush(); sys.stdout = sys.__stdout__; "
        python_str = "; ".join(setup_commands) + "; " if setup_commands else ""
        cmd = catch_command_stdout + python_str + reset_stdout + "from pytkdocs.cli import main; main(['--line-by-line'])"
```

Then you shouldn't need that if statement. What do you think? (Please no judgement on the variable names I just threw this together 🙈 )

**Comment by RDIL** [comment]
Hey, sorry for not responding sooner, I was asleep.  So this happens on https://gitpod.io, but not in CI or locally on my machine, which is interesting.  Maybe this is because I have gitpod pre-configured to run `mkdocs serve` as soon as the workspace is opened.  Not quite sure why this is happening though.

**Comment by pawamoy** [comment]
@rossmechanic, thank you very much for looking into this! And thanks for the snippet (no judgement :smile:)! I've refactored it in the following snippet. However if Python itself is executing a pre-script, faking sys.stdout might happen too late.

@RDIL no problem! Is it possible to patch an installed Python library on gitpod.io? If yes, could you try to apply this patch to mkdocstrings to see if it fixes the issue?

```diff
diff --git a/src/mkdocstrings/handlers/python.py b/src/mkdocstrings/handlers/python.py
index 88e8da3..f50d3f1 100644
--- a/src/mkdocstrings/handlers/python.py
+++ b/src/mkdocstrings/handlers/python.py
@@ -125,13 +125,27 @@ class PythonCollector(BaseCollector):
         """
         log.debug("mkdocstrings.handlers.python: Opening 'pytkdocs' subprocess")
         env = os.environ.copy()
+        env["PYTHONUNBUFFERED"] = "1"
 
-        python_str = "; ".join(setup_commands) + "; " if setup_commands else ""
-        cmd = python_str + "from pytkdocs.cli import main; main(['--line-by-line'])"
+        if setup_commands:
+            # prevent the Python interpreter or the setup commands
+            # from writing to stdout as it would break pytkdocs output
+            commands = [
+                "import sys",
+                "from io import StringIO",
+                "from pytkdocs.cli import main as pytkdocs",
+                "sys.stdout = StringIO()",  # redirect stdout to memory buffer
+                *setup_commands,
+                "sys.stdout.flush()",
+                "sys.stdout = sys.__stdout__",  # restore stdout
+                "pytkdocs(['--line-by-line'])"
+            ]
+            cmd = "; ".join(commands)
+        else:
+            cmd = ["pytkdocs", "--line-by-line"]
 
-        env["PYTHONUNBUFFERED"] = "1"
         self.process = Popen(  # noqa: S603,S607 (we trust the input, and we don't want to use the absolute path)
-            ["python", "-c", cmd], universal_newlines=True, stderr=PIPE, stdout=PIPE, stdin=PIPE, bufsize=-1, env=env,
+            cmd, universal_newlines=True, stderr=PIPE, stdout=PIPE, stdin=PIPE, bufsize=-1, env=env,
         )
 
     def collect(self, identifier: str, config: dict) -> Any:
```

Otherwise could you tell us if the `PYTHONSTARTUP` environment variable is defined, or if running `python -Sc "import site"` outputs anything (even a blank line)?

**Comment by RDIL** [comment]
I can try it out.

**Comment by RDIL** [comment]
Hey @pawamoy, I tried the patch but it has just been frozen for 15 minutes.  From the output of `mkdocs-plugin-progress`, I can see it has frozen on `INFO    -  Processing page "libraries/filehandlers/api.md"...`, which is one of the pages I use mkdocstrings on.

**Comment by pawamoy** [comment]
Hmmm forget about it. I'm trying it myselfin gitpod.io on your repo, and the error happens only when trying to collect filehandlers.

**Comment by pawamoy** [comment]
Really not sure to understand what's happening here :sweat_smile: 

Thank you for trying it out @RDIL 

I'll investigate a bit more.

**Comment by RDIL** [comment]
@pawamoy no worries!

**Comment by pawamoy** [comment]
Well I can confirm the issue only happens when running the process with `python -c`, and only through `mkdocs`... so weird.

**Comment by pawamoy** [comment]
OK seems to be related to pyenv:

```bash
/home/gitpod/.pyenv/shims/python3 -c "from mkdocs.commands.serve import serve; serve()"
# works

/home/gitpod/.pyenv/versions/3.8.2/bin/python3 -c "from mkdocs.commands.serve import serve; serve()"
# fails, the mkdocs script uses this path
```

**Comment by pawamoy** [comment]
If think they have some issues on gitpod.io with Python venvs because I just can't install anything in a virtualenv. It works, message says "Successfully installed..." but then `pip freezes` outputs nothing, and if I install again, it installs again and doesn't say "Requirement already satisfied".

**Comment by pawamoy** [comment]
**Conclusion**:
1. the bug is coming from gitpod's workspace setups, particularly how pyenv is used: calling python directly from pyenv's versions does not work while calling the shim works, and when scripts are installed with `pip install` their shebang point directly to the version, not the shim
1. mkdocstrings 0.11.0 is working correctly without setup commands
1. it will break if a setup commands writes to stdout
1. a fixed version of the snippet above fixes this issue
1. it will break if code imported while collecting documentation writes to stdout
1. this issue will be fixed in pytkdocs itself

In the meantime @RDIL you can use `python3 -c "from mkdocs.commands.serve import serve; serve()"` instead of `mkdocs serve` in your startup configuration!

I'll close this issue once the fix mentioned in point 4 is implemented!
